language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - cd server
  - pip install -r requirements.txt
  - python src/manage.py test && flake8

notifications:
  email:
    recipients:
      - kiokobenedict@gmail.com
    on_success: never
    on_failure: always

