language: python
python:
  - "3.8"

services:
  - docker

before_script: 
  - cd server
  - pip install docker-compose

script:
  - cd server
  - python src/manage.py test && falke8

notifications:
  email:
    recipients:
      - kiokobenedict@gmail.com
    on_success: never
    on_failure: always
