language: python
python:
  - "3.8"

services:
  - docker
  - postgresql

before_script:
  - pip install docker-compose
  - psql -c 'create database startups;' -U postgres

script:
  - cd server
  - pip install -r requirements.txt
  - python src/manage.py test

notifications:
  email:
    recipients:
      - kiokobenedict@gmail.com
    on_success: never
    on_failure: always

