language: python
python:
  - "3.8"

services:
  - docker

before_script: 
  - pip install docker-compose
  - docker-compose up --build

script:
  - cd server
  - pip install -r requirements.txt
  - docker-compose run app sh -c "python manage.py test && flake8"

notifications:
  email:
    recipients:
      - kiokobenedict@gmail.com
    on_success: never
    on_failure: always

