language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run sh -c "python src/manage.py test && falke8" -f ./server

notifications:
  email:
    recipients:
      - kiokobenedict@gmail.com
    on_success: never
    on_failure: always